sudo: required
services:
  - docker

before_install:
  - docker build -t leonvz/docker-react -f Dockerfile.dev .

script:
  - docker run leonvz/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReact"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-695457323481"
  bucket_path: "DockerReact"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"



    